# What is PyTorch?

### Tensors in PyTorch

Tensors are data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors in PyTorch are similar to NumPy's arrays; ndarrys, except that tensors can run on GPUs or other hardware accelerators. Tensors and NumPy share the underlying memories.


In other words, Tensors are multidimensional arrays.

PyTorch supports multiple types of tensors:
1. FloatTensor : 32-bit
2. DoubleTensor : 64-bit
3. HalfTensor : 16-bit
4. IntTensor : 32-bit
5. LongTensor : 64-bit

In [1]:
import torch
import numpy as np 

In [2]:
# Initialize two arrays
a = np.array(2)
b = np.array(1)
print(a, b)

2 1


The above are the NumPy arrays that we have initialized. Lets perform some mathematical operations.

In [3]:
print(a + b)

3


In [4]:
print(b - a)

-1


In [5]:
print(a * b)

2


In [6]:
print(a / b)

2.0


Now lets initialize some Tensors

In [7]:
a = torch.tensor(2)
b = torch.tensor(1)
print(a, b)

tensor(2) tensor(1)


Lets perform some operations

In [8]:
print(a + b)

tensor(3)


In [9]:
print(b - a)

tensor(-1)


In [10]:
print(a * b)

tensor(2)


In [11]:
print(a / b)

tensor(2.)


The codes are exactly the same in NumPy and PyTorch

## Matrix Initialization

Lets take a matrix of 3x3 having all zero. We will do this in NumPy.

In [12]:
a = np.zeros((3,3))
print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


Now, Lets do the same task in PyTorch.

In [13]:
a = torch.zeros((3,3))
print(a)
print(a.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])


As we see, PyTorch and NumPy have the same *zeros()* function. 

 Lets initialize matrix with random numbers in NumPy

In [14]:
# Set a random seed for NumPy
np.random.seed(42)

In [15]:
# matrix of random numbers
a = np.random.randn(3,3)
a

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

The *random.randn()* function returns random numbers that follow a standard normal distribution.

 Lets initialize matrix with random numbers in PyTorch

In [16]:
torch.manual_seed(42)

In [17]:
a = torch.randn(3,3)
a

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

## Matrix Operations

First, we do this on NumPy

In [18]:
np.random.seed(42)

In [19]:
a = np.random.randn(3,3)
b = np.random.randn(3,3)
print('a:', a)
print('b:', b)

a: [[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]
b: [[ 0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783]
 [-0.56228753 -1.01283112  0.31424733]]


In [20]:
print(np.add(a, b), "\n")

[[ 1.0392742  -0.60168199  0.18195878]
 [ 1.76499213 -2.14743362 -1.95905479]
 [ 1.01692529 -0.24539639 -0.15522705]] 



In [21]:
print(np.subtract(a, b), "\n")

[[-0.04584589  0.32515339  1.11341829]
 [ 1.28106758  1.67912687  1.49078088]
 [ 2.14150034  1.78026585 -0.78372172]] 



In [22]:
print(np.dot(a, b), "\n")

[[-0.12814468 -0.62164688  0.21069439]
 [ 0.90133115 -0.02065676 -0.3790019 ]
 [ 1.30648762 -1.7246546  -2.20677932]] 



In [23]:
print(np.divide(a, b), "\n")

[[ 0.9155008   0.29835784 -1.39069607]
 [ 6.29449313  0.12238321  0.13573803]
 [-2.80855031 -0.75771243 -1.49396459]] 



Now, let's do it in PyTorch

In [24]:
torch.manual_seed(42)

In [25]:
a = torch.randn(3,3)
b = torch.randn(3,3)
print('a:', a)
print('b:', b)

a: tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])
b: tensor([[ 0.2674,  0.5349,  0.8094],
        [ 1.1103, -1.6898, -0.9890],
        [ 0.9580,  1.3221,  0.8172]])


In [26]:
print(torch.add(a, b), '\n')

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]]) 



In [27]:
print(torch.sub(a, b), '\n')

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]]) 



In [28]:
print(torch.mm(a, b), '\n')

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]]) 



In [29]:
print(torch.div(a,b), '\n')

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]]) 



Note: *mm()* function of PyTorch is similar to dot product of NumPy.

## Matrix Transpose

Lets first do it in NumPy.

In [30]:
a = np.random.randn(3,3)
print(a, '\n')

[[-0.90802408 -1.4123037   1.46564877]
 [-0.2257763   0.0675282  -1.42474819]
 [-0.54438272  0.11092259 -1.15099358]] 



In [31]:
print(np.transpose(a))

[[-0.90802408 -0.2257763  -0.54438272]
 [-1.4123037   0.0675282   0.11092259]
 [ 1.46564877 -1.42474819 -1.15099358]]


Now, in PyTorch

In [32]:
a = torch.randn(3,3)
print(a, '\n')

tensor([[-0.7658, -0.7506,  1.3525],
        [ 0.6863, -0.3278,  0.7950],
        [ 0.2815,  0.0562,  0.5227]]) 



In [33]:
torch.t(a)

tensor([[-0.7658,  0.6863,  0.2815],
        [-0.7506, -0.3278,  0.0562],
        [ 1.3525,  0.7950,  0.5227]])

## Tensor Operations

In [34]:
a = np.array(1)

In [35]:
b = torch.tensor(1)

In [36]:
print(a)
print(b)

1
tensor(1)


In [37]:
type(a), type(b)

(numpy.ndarray, torch.Tensor)

### Concatenating Tensors

In [38]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
print(a, '\n')
print(b)

tensor([[1, 2],
        [3, 4]]) 

tensor([[5, 6],
        [7, 8]])


In [39]:
#Concatenating vertically
torch.cat((a, b))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [40]:
#Concatenating horizontally
torch.cat((a, b), dim = 1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

### Reshape the Tensors

In [41]:
torch.manual_seed(42)

In [42]:
a = torch.randn(2, 4)
print(a)
a.shape

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380]])


torch.Size([2, 4])

In [43]:
#reshape
b = a.reshape(1,8)
print(b)
b.shape

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380]])


torch.Size([1, 8])

Lets convert NumPy arrays to tensors.

In [44]:
a = np.array([[1,2],[3,4]])
print(a, '\n')

[[1 2]
 [3 4]] 



In [45]:
tensor = torch.from_numpy(a)
print(tensor)

tensor([[1, 2],
        [3, 4]])
